#!/bin/bash

#get params
A=$1
B=$2

#default values
A="${A:-A}"
B="${B:-B}"


function concatNtime {
    local c=''
    for (( i=1; i<=$2; i++ ))
    do
        c+="$1"
    done
    echo $c
}

function main {
    for i in {1..3}
    do
        git checkout $A && echo "$(concatNtime A $i)" > A.txt && git add . && git commit -m "Commit $(concatNtime A $i)" && git checkout $B && echo "$(concatNtime B $i)" > B.txt && git add . && git commit -m "Commit $(concatNtime B $i)"
    done
}

echo "" > A.txt && echo "" > B.txt && git add . && git commit -m reset && git branch $A && git branch $B && main
